name: Purge jsDelivr cache

on:
  push:
    branches:
      - main
    paths:
      - main.css

jobs:
  purge-jsdelivr-cache:
    runs-on: ubuntu-20.04
    steps:
      - uses: egad13/purge-jsdelivr-cache@v1
        with:
          url: |
            https://cdn.jsdelivr.net/gh/mms-gianni/argoviastars-website@main/main.css
